### ISSUE TITLE
Component documentation

### ISSUE THREAD

**Issue by Klikini** [Klikini/home-assistant.github.io#2]
# configuration.yaml example

```yaml
switch:
  - platform: rachio
    access_token: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    manual_run_mins: 10
```

# Configuration options

- **access_token** (_Required_): Rachio API Access Token
- **manual_run_mins** (_Optional_): For how long, in minutes, to turn on a station when the switch is enabled

# Getting your Rachio API Access Token

1. Log in at https://app.rach.io/
1. Click the user button at the top right
1. Click API Access Token
1. Copy it from the dialog that opens
